### ISSUE TITLE
Linux 运行时报错

### ISSUE THREAD

**Issue by Leao9203** [lideming/MusicCloudServer#1]
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/root/mcs/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=debian.10-x64&apphost_version=5.0.13

**Comment by Leao9203** [comment]
系统为 Debian 10 amd 64
内核版本号 4.19.0-18-amd64

**Comment by lideming** [comment]
是通过哪种方式运行的呢？
测试在 Docker `debian:10` 容器里 [安装 .NET 5.0 SDK](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#debian-10-) 后，在源码目录下 `dotnet run` 是可以运行的：

```bash
# 安装 .NET 5.0 SDK：
wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
sudo apt install dotnet-sdk-5.0

mkdir app
cd app

# 准备前端文件：
mkdir MusicCloud
cd MusicCloud
# （此处省略从 https://github.com/lideming/MusicCloud/actions/runs/1721778534 下载 dist.zip）
unzip dist.zip
cd ..

# 从源码运行 Server：
git clone https://github.com/lideming/MusicCloudServer
cd MusicCloudServer
dotnet run
```

**Comment by Leao9203** [comment]
运行的是 Server，从源码拉取后 `dotnet run` 然后就报错了

附一个 log
[log.txt](https://github.com/lideming/MusicCloudServer/files/7958545/log.txt)

**Comment by lideming** [comment]
```
System.IO.DirectoryNotFoundException: /root/app/MusicCloud/
```
默认的 `appsettings.json` 假设前端文件在 `../MusicCloud/` 里，这个报错是说这个路径不存在。

**Comment by Leao9203** [comment]
> 

可以前后端分离吗...想要这台服务器编译后只运行后端

**Comment by lideming** [comment]
把 `appsettings.json` 里的这个设置删掉就行了
```
"staticdir": "../MusicCloud",
```

**Comment by Leao9203** [comment]
![图片](https://user-images.githubusercontent.com/45661339/151672746-1ef84368-f2a1-488b-a35c-d8d3792aaa46.png)

现在看来已经不报错了，感谢开发者的耐心答疑
